const products = [
  {
    id: 'prod_kbd_01',
    name: 'Aether 75 Custom Keyboard',
    category: 'Keyboards',
    price: 19999,
    rating: 4.9,
    reviews_count: 124,
    reviewsCount: 124,
    description: 'Fully assembled gasket-mounted mechanical keyboard. Featuring custom lubed linear switches, premium dye-sub keycaps, and a solid CNC anodized aluminum case.',
    tag: 'Best Seller',
    image: '/products/prod_kbd_01.jpg',
    color: 'purple',
    stock: 8,
    specs: ['75% Compact ANSI Layout', 'Gasket Mounted Design', 'Custom Lubed Linear Red Switches', 'Hot-Swappable 5-Pin PCB', 'CNC Anodized Aluminum Shell'],
  },
  {
    id: 'prod_aud_02',
    name: 'Helix Studio Headphones',
    category: 'Audio',
    price: 24999,
    rating: 4.8,
    reviews_count: 88,
    reviewsCount: 88,
    description: 'High-fidelity open-back planar magnetic headphones. Extremely wide soundstage, precise transient response, and ultra-plush memory foam velour earpads.',
    tag: 'Audiophile Choice',
    image: '/products/prod_aud_02.jpg',
    color: 'pink',
    stock: 4,
    specs: ['Open-Back Planar Magnetic', '10Hz - 50kHz Frequency Range', '32 Ohms Low Impedance', 'Plush Memory Foam Velour Earpads', 'Detachable Dual-Sided OCC Cable'],
  },
  {
    id: 'prod_acc_03',
    name: 'Lumina RGB Desk Mat',
    category: 'Accessories',
    price: 3599,
    rating: 4.7,
    reviews_count: 231,
    reviewsCount: 231,
    description: 'Water-resistant, micro-textured weave desk pad. Outlined with addressable dual-zone RGB edge-lighting and a high-grip natural rubber base.',
    tag: 'Setup Highlight',
    image: '/products/prod_acc_03.jpg',
    color: 'blue',
    stock: 12,
    specs: ['900mm x 400mm Large Coverage', 'Water-Resistant Fabric Surface', 'Addressable Dual-Zone RGB Borders', 'Non-Slip Textured Rubber Base', 'Detachable Braided USB-C Cable'],
  },
  {
    id: 'prod_light_04',
    name: 'Spectra Ambient Smart Lamp',
    category: 'Accessories',
    price: 6499,
    rating: 4.6,
    reviews_count: 65,
    reviewsCount: 65,
    description: 'Interactive smart desk lamp with 16 million colors, custom developer programming integrations (REST API supported), and beautiful sound-reactive modes.',
    tag: 'Smart Light',
    image: '/products/prod_light_04.jpg',
    color: 'amber',
    stock: 5,
    specs: ['16 Million Addressable Colors', 'Developer API & REST Integrations', 'Sound-Reactive Ambient Modes', 'Adjustable Warm-to-Cool White', 'Companion Desktop Controller App'],
  },
  {
    id: 'prod_mous_05',
    name: 'Quantum Wireless Mouse',
    category: 'Keyboards',
    price: 9599,
    rating: 4.9,
    reviews_count: 156,
    reviewsCount: 156,
    description: 'Ultra-lightweight ergonomic gaming mouse. Features a 26K DPI optical sensor, custom responsive optical switches, and 120-hour uninterrupted battery life.',
    tag: 'Performance Pro',
    image: '/products/prod_mous_05.jpg',
    color: 'cyan',
    stock: 7,
    specs: ['52g Ultra-Lightweight Build', '26,000 DPI Custom Optical Sensor', 'Zero-Lag 2.4GHz Wireless Protocol', 'Responsive 90M Click Optical Switches', '120 Hours Continuous Battery Life'],
  },
  {
    id: 'prod_aud_06',
    name: 'Vortex USB Desk Microphone',
    category: 'Audio',
    price: 12999,
    rating: 4.7,
    reviews_count: 42,
    reviewsCount: 42,
    description: 'Professional studio-grade USB condenser microphone with zero-latency monitoring, hardware gain control, and built-in pop filter shock mount.',
    tag: 'Streamer Setup',
    image: '/products/prod_aud_06.jpg',
    color: 'red',
    stock: 6,
    specs: ['Triple-Capsule Condenser Array', 'Cardioid, Bidirectional, Omnidirectional', '24-Bit / 96kHz Studio Recording', 'Zero-Latency 3.5mm Headphone Jack', 'Hardware Gain Control & Mute Button'],
  },
  {
    id: 'prod_chair_07',
    name: 'Apex Ergo Office Chair',
    category: 'Accessories',
    price: 34999,
    rating: 4.8,
    reviews_count: 94,
    reviewsCount: 94,
    description: 'Highly adjustable ergonomic office chair. Designed with elastic mesh support, synchronous tilt adjustments, dynamic auto-adjusting lumbar locks, and soft padded 3D armrests.',
    tag: 'Premium Ergo',
    image: '/products/prod_chair_07.jpg',
    color: 'purple',
    stock: 3,
    specs: ['Breathable Mesh Back Support', 'Synchronous Auto-Tilt Lock', 'Adaptive Dynamic Lumbar Pillow', '3D Adjustable Height Armrests', 'Heavy-Duty Reinforced Nylon Base'],
  },
  {
    id: 'prod_mon_08',
    name: 'Horizon 34" Curved Monitor',
    category: 'Accessories',
    price: 54999,
    rating: 4.9,
    reviews_count: 73,
    reviewsCount: 73,
    description: '34-inch curved ultrawide desktop monitor. Sports a crisp WQHD (3440 x 1440) resolution, vibrant IPS panel, smooth 144Hz refresh rate, and 90W USB-C hub connectivity.',
    tag: 'Ultrawide Hub',
    image: '/products/prod_mon_08.jpg',
    color: 'blue',
    stock: 2,
    specs: ['34-inch 21:9 Curved IPS Screen', 'WQHD 3440 x 1440 Crystal Resolution', '144Hz Fluid Refresh Gaming Rate', 'Integrated 90W USB-C Docking Port', 'HDR400 Certified Vivid Display'],
  },
  {
    id: 'prod_stand_09',
    name: 'Solace Walnut Monitor Riser',
    category: 'Accessories',
    price: 4999,
    rating: 4.7,
    reviews_count: 112,
    reviewsCount: 112,
    description: 'Crafted solid american walnut wooden desk riser. Elevates monitor to ergonomic eye level, clearing underneath space for clean setup cable storage.',
    tag: 'Premium Walnut',
    image: '/products/prod_stand_09.jpg',
    color: 'amber',
    stock: 10,
    specs: ['100% Solid Premium American Walnut', 'Comfortable Ergonomic Elevating Lift', 'Powder-Coated Sleek Steel Legs', 'Non-Slip Cushioned Rubber Shoes', 'Max Weight Capacity up to 45kg'],
  },
  {
    id: 'prod_bar_10',
    name: 'Aura LED Monitor Lightbar',
    category: 'Accessories',
    price: 5999,
    rating: 4.8,
    reviews_count: 145,
    reviewsCount: 145,
    description: 'Sleek monitor lightbar that clamps atop screens. Illuminates desks without creating screen glare, featuring smart touch dimming and temperature color controls.',
    tag: 'Smart Lamp',
    image: '/products/prod_bar_10.jpg',
    color: 'cyan',
    stock: 8,
    specs: ['Asymmetric Desk Illumination Design', 'Eliminates Screen Glare completely', 'Stepless Color Temperature controls', 'Smart Auto-Dimming Brightness sensor', 'Convenient USB-Powered clamping arm'],
  },
];

module.exports = { products };
